#!/usr/bin/perl

use Sort::Naturally;
use warnings;
use strict;

my $title = "Gráfico";
if (@ARGV > 0) {
    $title = shift @ARGV;
}

my $bench_dir = "benchs";
my %benchs;

my $count = 1;
=pod
foreach my $filename (`ls $bench_dir`) {
    chomp $filename;
    my ($prog, $bench, $sample) = split /-/, $filename;
    $benchs{$bench . "_" . $count++} = {
            $prog . "_" . $sample  => -1,
    };
}
=cut


foreach my $filename (`ls $bench_dir`) {
    chomp $filename;
    if (! open FILE, "<", $bench_dir . "/" . $filename) {
        die "Cannot open FILE: $!";
    }
    my $instr = 1;
    my $cycles = 1;
    while (<FILE>) {
        chomp;
        if (/Instructions = /) {
            $instr = $';
        }
        if (/Cycles = /) {
            $cycles = $';
        }
    }
    my ($prog, $bench, $sample) = split /-/, $filename;
    $benchs{$bench}{$prog . "_" . $sample} = $instr/$cycles;
    close FILE;
}


my ($first) = keys %benchs;
print "# ";
foreach my $prog (nsort keys $benchs{$first}) {
    $prog =~ s/\.\w+//;
    print $prog . "\t";
}

print "\n";

$count = 1;
foreach my $bench (nsort keys %benchs) {
    print $count++ . "\t";
    foreach my $prog (keys $benchs{$bench}) {
        #print $bench . " => " . $prog . " => " . $benchs{$bench}{$prog} . "\n";
        print $benchs{$bench}{$prog} . "\t";
    }
    print "# $bench\n";
}

my $xtics = "set xtics (";
$count = 1;
foreach (nsort keys %benchs) {
    $xtics .= "\"" . $_ . "\" " . $count++ . ", ";
#    print $_ . ": " . $benchs{$_} . "\n";
}

$xtics =~ s/, $//g;
$xtics .= ")\n";

if (! open FILE, ">", "plot.settings") {
    die "Can't open plot.settings";
}
print FILE 'set autoscale' . "\n" .
    "set title \"$title\"" . "\n" .
    'set xlabel "Parâmetros"' . "\n" .
    'set ylabel "IPC"' . "\n" .
    'set key outside' . "\n" .
    $xtics . 
#    'set xtics ("set_32" 1,"set_64" 2,"set_256" 3)' . "\n\t" .
    'set style line 1 lw 4 lc rgb "#7A0000"' . "\n" .
    'set style line 2 lw 4 lc rgb "#FA304A"' . "\n" .
    'set style line 3 lw 4 lc rgb "#006400"' . "\n" .
    'set style line 4 lw 4 lc rgb "#ADF72F"' . "\n" .
    'set style line 5 lw 4 lc rgb "#00008B"' . "\n" .
    'set style line 6 lw 4 lc rgb "#1E90FF"' . "\n" .
    'plot "out.dat" using 1:2 with line ls 1 title "lista_denso",\\' . "\n\t" .
    '"out.dat" using 1:3 with line ls 2 title "lista_esparso",\\' . "\n\t" .
    '"out.dat" using 1:4 with line ls 3 title "heap_denso",\\' . "\n\t" .
    '"out.dat" using 1:5 with line ls 4 title "heap_esparso",\\' . "\n\t" .
    '"out.dat" using 1:6 with line ls 5 title "matriz_denso",\\' . "\n\t" .
    '"out.dat" using 1:7 with line ls 6 title "matriz_esparso"' . "\n".
    "set terminal pngcairo size 800,600\n" .
    "set output 'bench.png'\n" .
    "replot\n" .
    "set term x11";

close FILE;
