#!/usr/bin/perl

use warnings;
use strict;

my $instr = -1;
my $cycles = 1;

while (<>) {
    chomp;
    if (/Instructions = /) {
        $instr = $';
    } elsif (/Cycles = /) {
        $cycles = $';
    }
}

print $instr . " / " . $cycles . " = " . ($instr / $cycles) . "\n";
